on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    uses: Zaperex-Test-Org/shared-workflows/.github/workflows/add-to-project.yaml@main
    with:
      project_id: 1
    secrets: inherit
